# Generated by Django 5.1.5 on 2025-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=50, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Жива', 'Жива'), ('Бафф', 'Бафф')], default='Жива', max_length=10, verbose_name='Статус работы'),
        ),
    ]
