# Generated by Django 5.1.5 on 2025-02-01 20:04

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Верифицированн', 'Верифицированн'), ('Стандартный', 'Верифицированн')], max_length=26, verbose_name='Статус пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_avatars/'),
        ),
    ]
