# Generated by Django 5.1.5 on 2025-02-01 20:05

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_status_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Верифицированн', 'Верифицированн'), ('Стандартный', 'Верифицированн')], default='Стандартный', max_length=26, verbose_name='Статус пользователя'),
        ),
    ]
