# Generated by Django 5.1.5 on 2025-02-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_status_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='graffgram\x08log\\static\\img\\default_avatar.jpg', null=True, upload_to='users_avatars/'),
        ),
    ]
