# Generated by Django 5.1.5 on 2025-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to='users_avatars/'),
        ),
    ]
