# Generated by Django 5.1.5 on 2025-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users_avatars/default_avatar.jpg', null=True, upload_to='users_avatars/'),
        ),
    ]
